### ISSUE TITLE
WrapExpiration has potential busy deadloop (CPU 100%)

### ISSUE THREAD

**Issue by w13915984028** [rancher/dynamiclistener#63]
In debugging https://github.com/harvester/harvester/issues/2558, I found it is caused by below API.

https://github.com/rancher/dynamiclistener/blob/master/listener.go#L167

```
func (l *listener) WrapExpiration(days int) net.Listener {
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		// busy-wait for certificate preload to complete
		for l.cert == nil {
			runtime.Gosched()
		}
```

Though I am not fully sure how this issue is produced, but when such condition is met, the `WrapExpiration` indeed causes deadloop.

**Comment by w13915984028** [comment]
@brandond @rebeccazzzz @guangbochen

**Comment by brandond** [comment]
When looking at how Rancher and K3s/rke2 I didn't see any cases where we didn't immediately bind a certificate, so the busy-wait seemed acceptable. If there are code paths that cause this to run for more than a handful of iteration then yeah we should sleep instead.

**Comment by w13915984028** [comment]
@brandond 

I had a further look,  this BUG looks to be related to a couple of code change:

(1)
the `tight loop` was add in this commit, it was not in the code before, original code just wait 30 seconds and then go further.  Current loop code, in fact will block there as long as `l.cert == nil`
https://github.com/rancher/dynamiclistener/commit/284cc004e84101e4a5b9fa50c00e101095db83f6
![image](https://user-images.githubusercontent.com/31133476/181195199-006ca00b-a561-47e0-baad-6f6c09697597.png)


(2) in this commit, an additional check ` !cert.IsValidTLSSecret(secret)` was added, it will return;  and it will cause (1) goes into busy endless loop

https://github.com/rancher/dynamiclistener/commit/b1d65efb6f8309327ed7beb41463056379ec18eb#diff-52136e2f401dea328d50069c304fe222eb004d0ca7b8b12e6e6c4adbc9df6979R411
![image](https://user-images.githubusercontent.com/31133476/181195430-306dc71f-d693-43e2-9e74-35421e884f8f.png)



In my ENV,   the `secret` looked to be a `nil` value, (2) returns but the `l.cert is nil`  , and (1) is always busy looping

```
time="2022-07-25T10:07:16Z" level=warning msg="dynamiclistener [::]:8443: no cached certificate available 
for preload - deferring certificate load until storage initialization or first client request, 
id:4 name:secret:
&Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},
Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}"
```

**Comment by brandond** [comment]
The tight loop was added because there were complaints that the certificate was not being renewed soon enough after the listener was started, and it was causing problems with the rancher webhook when the certificate expired and needed to be renewed. We can't block startup because the cert may be loaded async, but we do want to check for and renew it as soon as possible. The idea behind the busy-wait was that the dynamiclistener endpoint should always have a certificate loaded within a very short time after it is started, but it sounds like there are some cases (agent in particular) where this is not the case.

It would be nice if this project had a library of test cases that cover how it is used for rancher server / rancher agent / rancher webhooks / k3s / rke2 / rke. It seems like we keep fixing things for one team but then regressing them for another because the code is somewhat opaque in places and noone is aware of how other products depend on specific behaviors.

**Comment by w13915984028** [comment]
Summary of how to trouble-shooting this issue:

https://github.com/w13915984028/harvester-develop-summary/blob/main/harvester-pod-100-cpu-usage-issue-2558.md
